[default_values]
K0 = 5e22
V = 400.0
dt = 50.0
r_injection = 1.0
uniform_energy_injection_maximum = 101.0

[2d_models_common_settings]
theta_injection = 90.0
use_uniform_injection = true

[SolarProp_like_model_settings]
SolarProp_ratio = 0.02

[Geliosphere_model_settings]
Geliosphere_ratio = 0.2
K0_ratio = 5.0
C_delta = 8.7e-5
default_tilt_angle = 0.1

[advanced_settings]
remove_log_files_after_simulation = true
